config/routes.rb
Rails.application.routes.draw do

  root 'articles#index'

  get 'articles/:id/create-comment', to: "articles#create_comment"

  resources :articles, only: [:index, :show, :destroy] do
    get 'create_article', on: :new
    resources :comments
  end

end

app/models/article.rb
# Public: Methods for generating content within the app.
class Article < ActiveRecord::Base
  has_many :comments, dependent: :destroy

  # Public: Creates a new Comment, associated with an article
  # 
  # Example: 
  # 
  #   a = Article.first
  #   a.create_random_comment
  #   # => <Comment id: 111, name: "Tre Hahn", body: "The SQL system is down, 
  #         copy the multi-byte bus so...", article_id: 4, created_at: 
  #         "2015-03-02 17:07:54", updated_at: "2015-03-02 17:07:54">
  # 
  # Returns a Comment object, with id, name, body, article_id, and timestamps
  def create_random_comment
    self.comments.create(name: Faker::Name.name, body: Faker::Hacker.say_something_smart)
  end

  # Public: Creates a new Article
  # 
  # Example: 
  # 
  #   b = Article.create_random_article
  #   # => [["title", "alias ut"], ["body", "Iure reiciendis libero perferendis
  #         repudiandae. Est vitae soluta dolores iusto quia. Voluptatem rerum
  #         cupidate est. ..."],  ["created_at", "2015-03-02 17:11:39.833066"], 
  #         ["updated_at", "2015-03-02 17:11:39.833066"]]
  # 
  # Returns a Nested array with the title, body, and times for the new article.
  def self.create_random_article
    a = Article.new
    a.title = Faker::Lorem.words(Random.rand(2..8)).join(" ")
    a.body = Faker::Lorem.paragraph(Random.rand(65..85))
    a.save
    a     
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :article

  def self.seed_fake_comments
    0.upto(5) do 
      c = Comment.new
      c.name = Faker::Name.name
      c.body = Faker::Hacker.say_something_smart
      c.save
    end    
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  skip_before_filter :verify_authenticity_token
  
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  before_action :find_article, only: [:show, :create_comment, :destroy]
  before_action :set_cache_control_headers, only: [:index, :show]
  before_action :set_private, only: [:create_comment, :create_article]

  # All env, returns all Article objects.
  # In production, also sets surrogate key headers for the table_key and
  # record_key. "#{table_key}/#{article_id}"
  # 
  # Sets a table_key of 'articles', and a record_key for each article object.
  def index
    @articles = Article.all
    if Rails.env == "production"
      set_surrogate_key_header 'articles', @articles.map(&:record_key)
    end
  end

  # In production, sets a surrogate key for the current article.
  # 
  # 
  # Example: 
  # 
  #   Article[75]
  #   Response headers:
  #   Surrogate-Key:articles/75
  def show
    if Rails.env == "production"
      set_surrogate_key_header @article.record_key
    end
  end

  # Creates a new comment for current article
  # If in production, all cached versions of current article are purged,
  # using the record_key, "articles/#{article_id}"
  def create_comment
    @article.create_random_comment
    if Rails.env == 'production'
      @article.purge
    end
    redirect_to article_path(@article)
  end

  # Creates a new article, and if in production purges the cache. 
  def create_article
    new_article = Article.create_random_article
      if Rails.env == "production"
        new_article.purge_all
      end
    redirect_to articles_url
  end

  # Deletes the current article.
  # If in production, purges cache with matching record_key, and then purges
  # the cache with matching table_key.
  def destroy
    @article.destroy
    if Rails.env == "production"
      @article.purge
      @article.purge_all
    end
    redirect_to articles_path    
  end

  private

  def find_article
    @article = Article.find(params[:id])
    redirect_to articles_path unless @article
  end

  # Private: Sets Cache-Control headers to not store content
  # Used for create methods.
  def set_private
    response.headers["Cache-Control"] = "no-cache, no-store, max-age=0, must-revalidate"
    response.headers["Pragma"] = "no-cache"
    response.headers["Expires"] = '-1'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/index.html.erb
<div class="center jumbotron">
  <h1>Articles</h1>
</div>

<section>
  <ul>
    <% @articles.each do |article| %>
      <li><%= link_to article.title.titleize, article_path(article) %></li>
    <% end %>
  </ul>
</section>

<div>
  <%= link_to 'Create new article', create_article_new_article_path, class: "btn btn-primary" %>
</div>

app/views/articles/show.html.erb
<div>
  <h1><%= @article.title.titleize %></h1>
</div>

<div>
  <%= @article.body.html_safe %>
</div>



<div>
  <h2>Comments</h2>
</div>

<div>
   <% @article.comments.each do |comment| %>
    <p><%= comment.name %> commented: 
    <%= comment.body %></p>    
  <% end %>
</div>

<%= link_to 'Back', articles_path, class: "btn btn-info" %>
<%= link_to 'Create new comment', "/articles/#{params[:id]}/create-comment", class: "btn btn-info" %>
<%= link_to 'Delete this article', article_path(@article), method: :delete, class: "btn btn-warning" %>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Fakeblog</title>
  <%= stylesheet_link_tag    'application', media: 'all'%>
  <%= javascript_include_tag 'application' %>
</head>
<body>

<div class="container">
  <%= yield %>  
</div>

</body>
</html>